### ISSUE TITLE
Which version of node is this project using? 

### ISSUE THREAD

**Issue by thomasingalls** [3vnt/holisticparallelogram#10]
1. there seems to be concern about server-side ES2015 in `precompile.js` and `package.json`
2. `.travis.yml` specifies node `v0.8`, `v0.10`
3. the travis service supports past `v5`
4. node `v0.10` doesn't support much of ES2015, but v5+ does (cf: https://kangax.github.io/compat-table/es6/#node5)

**Comment by Genevieve1722** [comment]
The readme specifies Node 0.10.x.
